# Generated by Django 5.2.1 on 2025-07-29 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from pathlib import Path

def populate(apps, schema_editor):
    pic_form = ["JPG", "PNG", "GIF", "TIFF", "WEBP", "SVG", "BMP", "HEIF"]
    vid_form = ["MP4", "AVI", "MOV", "WMV", "MKV", "WEBM"]

    save_path = str(f"{Path(__file__).resolve().parents[3]}\\saves")

    settings = {
        "save_loc": (True, save_path),
        "auto_items": False,
        "absolute_links": False,
        "related_links": True,
        "relative_links": False,
        #"auto_update": False,
    }

    Formats = apps.get_model('istos', 'Formats')
    for form in pic_form:
        obj = Formats(type = "pic", formName = form)
        obj.save()

    for form in vid_form:
        obj = Formats(type = "vid", formName = form)
        obj.save()

    Settings = apps.get_model('istos', "Settings")
    for key, value in settings.items():
        if(key == "save_loc"):
            on, path = value
            obj = Settings(settingName = key, on = on, link = path)
            obj.save()
        else:
            obj = Settings(settingName = key, on = value)
            obj.save()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vid', 'vid'), ('pic', 'pic')], max_length=3)),
                ('formName', models.CharField(max_length=4)),
                ('formSave', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('site', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('dateGrabbed', models.DateField(default=django.utils.timezone.now)),
                ('hasParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='istos.link')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingName', models.CharField(max_length=100)),
                ('on', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, null=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('dateGrabbed', models.DateField(default=django.utils.timezone.now)),
                ('saved', models.BooleanField(default=False)),
                ('dateSaved', models.DateField(null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istos.link')),
            ],
        ),
        
        migrations.RunPython(populate)
    ]
